services:
  db:
    image: postgres:13
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: macrespo
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - type: bind
        source: ./data_warehouse
        target: /opt
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  python:
    image: python:3
    volumes:
      - type: bind
        source: src
        target: /usr/src/app
